icons_format = "{icon}"

[theme]
theme = "dracula"
[theme.overrides]
idle_bg = "#000000"

[icons]
icons = "awesome6"

[[block]]
block = "cpu"
interval = 5
format = " $icon $utilization "
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "battery"
full_threshold = 100
driver = "upower"
good = 75
info = 50

[[block]]
block = "net"
format = "$icon {$ssid $signal_strength|Wired Connection}"
format_alt = "^icon_net_down $speed_down.eng(w:5) ^icon_net_up $speed_up.eng(w:5)"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available.eng(w:5, prefix_space:true, p:Gi)"
[[block.click]]
button = "left"
update = true

[[block]]
block = "memory"
format = " $icon $mem_used_percents"
interval = 5
warning_mem = 50
critical_mem = 75

[[block]]
block = "sound"
driver = "pulseaudio"
show_volume_when_muted = true
headphones_indicator = true
format = " $icon $volume"
step_width = 5
max_vol = 100

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "menu"
text = "\uf011 "
[[block.items]]
display = " -&gt; Power Off &lt;-"
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " -&gt;   Sleep   &lt;-"
cmd = "systemctl suspend"
[[block.items]]
display = " -&gt;  Reboot   &lt;-"
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"
